# Project information
site_name: Policy Editor Documentation
# defeine TOC or order of website-
nav:
  - Getting Started:
    - Introduction: 'index.md'
    - Installation procedures for the API: 'installation.md'
    - Application architecture overview: 'architecture.md'
    - API Endpoints: 'api.md'

site_author: Abdulrahman Olamilekan
site_description: >-
  This documentation explains how to use the Policy manager API and what it does

# Repository
repo_name: r-scheele/policy-editor-documentation
repo_url: https://github.com/r-scheele/policy-editor-documentation
# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime    
  # logo: PyTorch_logo_icon.svg




markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  
  
plugins:
  - search


copyright: |
  &copy; 2022 <a href="http://www.geobeyond.it/"  target="_blank" rel="noopener">Geobeyond Srl</a>